baseurl                 = "/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "welcome to the RUTH ZONE"
theme                   = "hugo-theme-sam"
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/favicon.ico"
    pygmentsStyle       = "monokai"                     # https://help.farbox.com/pygments.html
    pygmentsCodefences  = true
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "this has been ruth."

# Metadata
    description         = "Ruth's Cool Webpage"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/ruth.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "https://twitter.com/purrloftruth"
    text = "hey, what's up?"

[[params.mainMenu]]
    link = "https://twitch.tv/coralfluff"
    text = "it's your girl, ruth."

[[params.mainMenu]]
    link = "https://snouts.online/@purrl"
    text = "welcome to RUTH ZONE."
